name: Build and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GNU Octave
      run: |
        sudo apt-get install octave liboctave-dev
        octave --version
    - name: Install SPM12 in Octave
      run: |
        mkdir spm12 && curl -SL https://github.com/spm/spm12/archive/r7771.tar.gz | tar -xzC spm12 --strip-components 1
        curl -SL https://raw.githubusercontent.com/spm/spm-docker/master/octave/spm12_r7771.patch | patch -d spm12 -p3
        cd spm12/src && make PLATFORM=octave install && cd ../..
        octave --no-gui --no-window-system --silent --eval "addpath (fullfile (pwd, 'spm12')); savepath ();"
    - name: Install library in Octave
      run: octave --no-gui --no-window-system --silent --eval "addpath (pwd); savepath ();"
    - name: Run tests
      run: octave --no-gui --no-window-system --silent --eval "cd tests; results = spm_runtests; assert(all(~[results.Failed]))"
